FROM golang:1.21-alpine as modules

COPY go.mod go.sum /modules/
WORKDIR /modules
RUN go mod download

FROM golang:1.21-alpine as builder

COPY --from=modules /go/pkg /go/pkg
COPY . /build
WORKDIR /build

RUN CGO_ENABLED=0 GOOS=linux go build -o sidecar-injector
RUN printenv

FROM scratch
COPY --from=builder /build/sidecar-injector /

ENTRYPOINT ["/sidecar-injector"]