FROM golang:1.21-alpine as modules

COPY go.mod go.sum /modules/
WORKDIR /modules
RUN go mod download

FROM golang:1.21-alpine as builder

COPY --from=modules /go/pkg /go/pkg
COPY . /proxy
WORKDIR /proxy

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -tags migrate -o /bin/proxy ./cmd/opentelemetry

FROM scratch
WORKDIR /
COPY --from=builder /bin/proxy /

EXPORT 80 443

ENTRYPOINT ["/proxy"]