name: sidecar-injector
home: https://github.com/khuong02/otel-sidecar
version: 0.1.0
apiVersion: v2
keywords:
  - kubernetes
  - sidecar-injection
sources:
  - https://github.com/khuong02/otel-sidecar
