APP:
  NAME: service-test
  STAGE: LOCAL
  VERSION: 0.0.1

HTTP:
  PORT: 1234
  HOST: 0.0.0.0

SERVICE_PROXY:
  HOST: "0.0.0.0:8080"

TRACER:
  COLLECTOR_URL: "0.0.0.0:4317"
  INSECURE: "true"
  LANG: "NODE"
  SERVER_NAME_OVER: ""
  STD_OUT_TRACE: false
  CP_PATH: ""

