apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-sidecar
data:
  sidecars.yaml: |
    - name: proxy-agent
      containers:
        - name: proxy
          image: khuong02/proxy-otel:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80